### ISSUE TITLE
How is your is-module related to npm's is-module?

### ISSUE THREAD

**Issue by SnarkBoojum** [component/is-module#1]
Hi,

I wanted to package is-module for the Debian distribution, and did so starting from the is-module available on npmjs.com ; unfortunately that one points to a 404 homepage on github.

Your github is alive, but I have a hard time knowing what is the difference between your version and npm's -- the license is the same including the copyright assignment.

I'm at loss what to do...

**Comment by timaschew** [comment]
It's just a fork and compatible with https://github.com/componentjs/component

**Comment by timaschew** [comment]
I don't know where it is gone, seems that someone deleted the repository, its neither in the component organization nor in the componentjs organization.

@ianstormtaylor @jonathanong
maybe you know what happened?

**Comment by jonathanong** [comment]
i probably deleted it. do u want the package?

**Comment by SnarkBoojum** [comment]
Well, what bothers me the most is that npmjs and this repository both are "is-module". To get a package in Debian, I would need some place where I can point to official upstream releases, but : npmjs points to a 404, and here there is no release.

My goal is to package rollup for Debian, but that requires rollup-plugin-node-resolve, and that needs is-module...

If you could tag a release here and make npmjs' is-module point to it, that would definitely clarify the situation!

Thanks for the quick answers!

**Comment by timaschew** [comment]
@jonathanong if you add me on npmjs I can update the readme to point to this repo, but wait...

I can just transfer this repo to the component organization again then the link will work again ;)

**Comment by SnarkBoojum** [comment]
Do as you please : as long as I have a definite upstream, it's ok for me :-)

**Comment by timaschew** [comment]
done ;)

**Comment by SnarkBoojum** [comment]
Hmmmm... what is done?

**Comment by timaschew** [comment]
The link on npm is working now, I transfered the project to component.

(I forked it to my personal account as well, just in case it will be
deleted in future again ;)


Julien Puydt <notifications@github.com> schrieb am So. 20. Aug. 2017 um
17:17:
